const DATA = {};
const routes = {};

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHtml = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));

async function loadData(){
  const files=['school','academics','facilities','faculty','results','documents','infrastructure','admissions','gallery'];
  const values=await Promise.all(files.map(f=>fetch(`/data/${f}.json`).then(r=>r.json())));
  files.forEach((f,i)=>DATA[f]=values[i]);
}

const links = [
  ['Home','/'],['About','/about'],['Academics','/academics'],['Admissions','/admissions'],['Campus','/campus/facilities'],['Activities','/student-life'],['Disclosure','/disclosure'],['Rules','/rules-regulations'],['Contact','/contact']
];

function layout(content){
  document.title = `${currentTitle()} · Nalanda English Medium Hr. Sec. School – Bhilai`;
  return `
  <div class="nav-wrap"><nav class="container nav neu" aria-label="Primary navigation"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">N</span><span class="brand-copy"><strong>Nalanda English Medium Hr. Sec. School</strong><span>Bhilai · Kurud · Durg</span></span></a><div class="nav-links">${links.map(([t,h])=>`<a class="nav-link ${location.pathname===h?'active':''}" href="${h}">${t}</a>`).join('')}</div><a class="neu-btn primary nav-cta" href="/admissions">Admission Enquiry</a><button class="menu-btn" id="menu-open" aria-label="Open navigation">☰</button></nav></div>
  <aside class="mobile-drawer" id="mobile-drawer" aria-label="Mobile navigation"><button class="drawer-close" id="menu-close" aria-label="Close navigation">×</button>${links.map(([t,h])=>`<a class="drawer-link" href="${h}">${t}</a>`).join('')}<a class="neu-btn primary" href="/contact">Contact School</a></aside>
  <main id="app-content">${content}</main>
  ${footer()}
  <div class="lightbox" id="lightbox" aria-hidden="true"><div class="lightbox-panel"><button class="lightbox-close" id="lightbox-close" aria-label="Close gallery">×</button><div class="lightbox-placeholder" id="lightbox-body"></div></div></div>`;
}

function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div><h4>Nalanda</h4><p>${DATA.school.name}</p><p>${DATA.school.address}</p><p><strong>Affiliation:</strong> ${DATA.school.affiliationNo}<br><strong>School Code:</strong> ${DATA.school.schoolCode}</p></div><div><h4>Quick Links</h4><div class="footer-list"><a href="/about">About</a><a href="/academics">Academics</a><a href="/admissions">Admissions</a><a href="/campus/facilities">Facilities</a><a href="/campus/gallery">Gallery</a><a href="/contact">Contact</a></div></div><div><h4>Academics</h4><div class="footer-list"><a href="/academics/calendar">Calendar</a><a href="/academics/book-list">Book List</a><a href="/academics/teachers">Teachers & Staff</a><a href="/academics/results">Results</a><a href="/disclosure">Public Disclosure</a></div></div><div><h4>Contact</h4><div class="footer-list"><a href="tel:+917884216647">0788-4216647</a><a href="tel:+917884216642">0788-4216642</a><a href="tel:+916266434635">6266434635</a><a href="mailto:${DATA.school.email}">${DATA.school.email}</a></div></div></div><div class="copyright"><span>© Nalanda English Medium Hr. Sec. School – Bhilai</span><span>Privacy · Website Use · Accessibility · Public Disclosure</span></div></div></footer>`}

function pageHero(kicker,title,desc=''){return `<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Home</a> / ${escapeHtml(title)}</div><div class="kicker">${kicker}</div><h1>${title}</h1>${desc?`<p style="max-width:760px;color:var(--muted);font-size:1.05rem">${desc}</p>`:''}</div></section>`}
function card(icon,title,desc,extra=''){return `<article class="card neu"><div class="icon" aria-hidden="true">${icon}</div><h3>${title}</h3><p>${desc}</p>${extra}</article>`}
function placeholder(label){return `<div class="visual-placeholder"><div><strong>[${label}]</strong><small>Replace this placeholder with the school’s official asset.</small></div></div>`}

routes['/'] = () => `<div class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="kicker">CBSE • Senior Secondary • Kurud, Bhilai</div><h1>${DATA.school.tagline}</h1><p>Modern presentation for a long-standing educational institution, centred on clarity, trust, discipline and academic development.</p><div class="hero-actions"><a class="neu-btn primary" href="/about">Explore Our School →</a><a class="neu-btn" href="/admissions">Admission Enquiry</a></div><div class="hero-meta"><span>⌁ ${DATA.school.address}</span><span>◌ Affiliation ${DATA.school.affiliationNo}</span></div></div><div class="visual-shell">${placeholder('MAIN SCHOOL IMAGE')}</div></div></div>
<section class="section tight"><div class="container stats"><div class="stat neu"><div class="mini">CBSE Affiliated</div><div class="value">${DATA.school.affiliationNo}</div><div class="label">Affiliation number</div></div><div class="stat neu"><div class="mini">School Code</div><div class="value">${DATA.school.schoolCode}</div><div class="label">Institution code</div></div><div class="stat neu"><div class="mini">Campus Area</div><div class="value">${DATA.school.campusArea}</div><div class="label">Published infrastructure figure</div></div><div class="stat neu"><div class="mini">Classrooms</div><div class="value">${DATA.school.classrooms}</div><div class="label">Published infrastructure figure</div></div></div></section>
<section class="section"><div class="container split"><div class="image-placeholder">${placeholder('PRIMARY SCHOOL IMAGE')}</div><div class="copy"><div class="kicker">Welcome to Nalanda</div><h3>A clearer, more credible digital front door for the school.</h3><p>The institution’s history traces back to the Kerala Cultural Association, formed in 1978, and Malinda Nursery School, established in 1979. The school later developed to higher-secondary level in Kurud and is affiliated with CBSE.</p><p>This redesign preserves the verified facts while removing legacy copy and presenting the school with a more modern information architecture.</p><a class="neu-btn secondary" href="/about">Discover Our Story →</a></div></div></section>
<section class="section tight"><div class="container"><div class="section-heading"><div class="kicker">Leadership</div><h2>Principal’s message</h2><p>A clean leadership section ready for the official message and photograph.</p></div><div class="split"><div class="image-placeholder">${placeholder('PRINCIPAL PHOTO')}</div><div class="card neu"><div class="kicker">Principal</div><h3 style="font-size:1.7rem">${DATA.school.principal.name}</h3><p><strong>${DATA.school.principal.qualification}</strong></p><div class="callout" style="margin:20px 0">[Principal’s official message to be added here.]</div></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div class="kicker">Vision & Values</div><h2>What the institution stands for</h2><p>These themes are based on the school’s published history and educational aims; they are not presented as a fabricated mission statement.</p></div><div class="grid-3">${[['◈','Discipline','A long-standing emphasis in the institution’s published history.'],['◇','Character Building','A stated aim of the founding association.'],['◍','Academic Development','Education is positioned as a central institutional purpose.'],['✦','Physical Development','Physical development is named among the founding aims.'],['◉','Cultural Development','Cultural and social activity form part of the institution’s origins.'],['✧','Holistic Education','A balanced framing across academic, physical and cultural development.']].map(x=>card(x[0],x[1],x[2])).join('')}</div></div></section>
<section class="section tight"><div class="container"><div class="section-heading"><div class="kicker">Academics</div><h2>Learning stages, without clutter.</h2></div><div class="tabs" role="tablist">${DATA.academics.stages.map((s,i)=>`<button class="tab ${i===0?'active':''}" role="tab" data-tab="${s.id}">${s.title}</button>`).join('')}</div>${DATA.academics.stages.map((s,i)=>`<div class="tab-panel ${i===0?'active':''}" data-panel="${s.id}"><div class="card neu"><div class="subjects">${s.items.map(x=>`<span class="pill">${x}</span>`).join('')}</div></div></div>`).join('')}</div></section>
<section class="section"><div class="container"><div class="section-heading"><div class="kicker">Facilities</div><h2>Focused spaces for focused learning.</h2></div><div class="grid-4">${DATA.facilities.slice(0,8).map(f=>`<article class="card neu facility"><div class="icon">${f.icon}</div><h3>${f.title}</h3><p>${f.description}</p></article>`).join('')}</div><div style="margin-top:20px"><a class="neu-btn" href="/campus/facilities">Explore Facilities →</a></div></div></section>
<section class="section tight"><div class="container split"><div class="copy"><div class="kicker">Admissions</div><h3>A direct path from enquiry to information.</h3><p>Admission rules are presented from the school’s published guidance. Unverified age criteria, dates and workflow steps are deliberately left as placeholders.</p><a class="neu-btn primary" href="/admissions">View Admission Guidelines →</a></div><div class="card neu"><div class="notice"><div class="icon">!</div><div><h3 style="margin-top:0">At a glance</h3><p>${DATA.admissions.principle}</p></div></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div class="kicker">Published Board Results</div><h2>Three years of reported outcomes.</h2></div><div id="home-results"></div></div></section>
<section class="section tight"><div class="container split"><div class="card neu"><div class="kicker">Mandatory Public Disclosure</div><h3>Documents, records and school information in one place.</h3><p>The public disclosure structure is designed as an official-looking document centre, while missing source PDFs remain clearly marked as placeholders.</p><a class="neu-btn secondary" href="/disclosure">Open Disclosure Centre →</a></div><div class="map-placeholder neu"><div class="map-inner"><div><strong>Map area</strong><div style="color:var(--muted);margin-top:6px">Official coordinates or embedded map to be supplied.</div></div></div></div></div></section>
<section class="section tight"><div class="container neu" style="padding:28px"><div class="section-heading" style="margin-bottom:16px"><div class="kicker">Latest Updates</div><h2 style="font-size:2rem">Notice architecture is ready.</h2><p>No live announcements are invented here. Add official circulars, notices and school updates through the structured content layer.</p></div><div class="callout">[Add official school notice here]</div></div></section>`;

routes['/about'] = () => `<section class="section"><div class="container">${pageHero('About the school','About N.E.M.H.S.S','A professionally rewritten institutional story grounded in the school’s published history.') }<div class="split"><div class="image-placeholder">${placeholder('ABOUT SCHOOL IMAGE')}</div><div class="copy"><h3>From a community initiative to a higher-secondary institution.</h3><p>Kerala Cultural Association (KCA) was formed in 1978 in the CGB colony. Its published aims included cultural and social activity, sound and liberal education, discipline, character building, physical development and cultural development.</p><p>Malinda Nursery School was established in 1979. The institution subsequently developed to higher-secondary level in Kurud and operates as Nalanda English Medium Hr. Sec. School – Bhilai.</p><p>The school is affiliated with the Central Board of Secondary Education, New Delhi, and prepares students for Class X and Class XII board examinations.</p></div></div></div></section>`;
routes['/about/journey'] = () => `<section class="section"><div class="container">${pageHero('Our Journey','Our Journey','A clean timeline using only the available published history.') }<div class="neu" style="padding:32px"><div class="timeline">${[['1978','Formation of Kerala Cultural Association','KCA was formed in the CGB colony with educational, social, cultural and development aims.'],['1979','Malinda Nursery School','The nursery school was established as an early educational initiative.'],['Growth','Institutional Development','The institution expanded and developed to higher-secondary level in Kurud.'],['Present','Nalanda English Medium Hr. Sec. School – Bhilai','The school is affiliated with CBSE and prepares students for Class X and Class XII board examinations.']].map(x=>`<div class="timeline-item"><div class="timeline-year">${x[0]}</div><div class="timeline-title">${x[1]}</div><div style="color:var(--muted)">${x[2]}</div></div>`).join('')}</div></div></div></section>`;
routes['/about/principal'] = () => `<section class="section"><div class="container">${pageHero('Leadership','Principal’s Message','Official message placeholder — no personal quotation is fabricated.') }<div class="split"><div class="image-placeholder">${placeholder('PRINCIPAL PHOTO')}</div><div class="card neu"><div class="kicker">Principal</div><h3>${DATA.school.principal.name}</h3><p><strong>${DATA.school.principal.qualification}</strong></p><p class="callout">[Principal’s official message to be added here.]</p></div></div></div></section>`;
routes['/about/vision-values'] = () => `<section class="section"><div class="container">${pageHero('Vision & Values','Vision & Values','Themes drawn from the school’s published institutional history; not presented as an invented official mission statement.') }<div class="grid-3">${[['◈','Discipline','A published founding emphasis.'],['◇','Character Building','A stated aim of KCA’s educational purpose.'],['◍','Academic Development','A central reason for the institution’s establishment and growth.'],['✦','Physical Development','Explicitly listed among the founding aims.'],['◉','Cultural Development','Part of the institution’s original social and cultural purpose.'],['✧','Holistic Education','A balanced interpretation of the published aims across domains.']].map(x=>card(x[0],x[1],x[2])).join('')}</div></div></section>`;

routes['/academics'] = () => `<section class="section"><div class="container">${pageHero('Academics','Academic Overview','A structured overview of the school’s published academic stages and subjects.') }<div class="grid-3">${DATA.academics.stages.map(s=>`<div class="card neu"><div class="kicker">Academic Stage</div><h3>${s.title}</h3><div class="subjects" style="margin-top:12px">${s.items.map(i=>`<span class="pill">${i}</span>`).join('')}</div></div>`).join('')}</div><div class="section tight"><div class="section-heading"><div class="kicker">Curriculum</div><h2>Subjects listed by the school</h2></div><div class="tabs"><button class="tab active" data-tab="core">School Subjects</button><button class="tab" data-tab="senior">Senior Secondary</button></div><div class="tab-panel active" data-panel="core"><div class="card neu"><div class="subjects">${DATA.academics.subjects.map(s=>`<span class="pill">${s}</span>`).join('')}</div></div></div><div class="tab-panel" data-panel="senior"><div class="card neu"><div class="subjects">${DATA.academics.seniorSubjects.map(s=>`<span class="pill">${s}</span>`).join('')}</div></div></div></div></div></section>`;
routes['/academics/curriculum'] = routes['/academics'];
routes['/academics/calendar'] = () => `<section class="section"><div class="container">${pageHero('Academics','Academic Calendar','Official dates are intentionally not invented.') }<div class="card neu"><h3>Academic sessions</h3><p>Prepare official calendar PDFs or structured dates for future sessions.</p><div class="grid-3" style="margin-top:18px"><div class="card neu"><h3>2025–26</h3><p>[Upload official academic calendar PDF]</p></div><div class="card neu"><h3>2026–27</h3><p>[Upload official academic calendar PDF]</p></div><div class="card neu"><h3>Future Years</h3><p>[Add official calendar when published]</p></div></div></div></div></section>`;
routes['/academics/book-list'] = () => `<section class="section"><div class="container">${pageHero('Academics','Book List','Searchable architecture ready for official book-list documents.') }<div class="filters"><div class="tabs" id="book-tabs">${['All','Nursery','KG I','KG II','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'].map((x,i)=>`<button class="tab ${i===0?'active':''}" data-book-filter="${x}">${x}</button>`).join('')}</div><div class="search"><input id="book-search" placeholder="Search book list…" aria-label="Search book list"></div></div><div class="card neu"><h3>Official source</h3><p>[BOOK LIST PDF – 2025–26]</p><p class="form-note">Book titles are not fabricated. Replace the placeholder with the latest official school document.</p></div></div></section>`;
routes['/academics/teachers'] = () => `<section class="section"><div class="container">${pageHero('Academics','Teachers & Staff','A searchable staff directory built around verified published details only.') }<div class="filters"><div class="tabs"><button class="tab active" data-staff-filter="All">All</button><button class="tab" data-staff-filter="Principal">Principal</button><button class="tab" data-staff-filter="Vice Principal">Vice Principal</button><button class="tab" data-staff-filter="PGT">PGT</button><button class="tab" data-staff-filter="TGT">TGT</button><button class="tab" data-staff-filter="PRT">PRT</button></div><div class="search"><input id="staff-search" placeholder="Search staff…" aria-label="Search staff"></div></div><div class="grid-3" id="staff-grid"></div></div></section>`;
routes['/academics/results'] = () => `<section class="section"><div class="container">${pageHero('Academics','Published Board Results','Class X and Class XII outcomes supplied in the project brief and shown as historical results.') }<div class="tabs"><button class="tab active" data-result-tab="classX">Class X</button><button class="tab" data-result-tab="classXII">Class XII</button></div><div id="results-page"></div></div></section>`;

routes['/admissions'] = () => `<section class="section"><div class="container">${pageHero('Admissions','Admission Enquiry','A direct, accessible enquiry flow with no invented backend submission.') }<div class="split"><div><div class="card neu"><div class="kicker">Published rule</div><h3>${DATA.admissions.principle}</h3></div><div style="height:18px"></div>${DATA.admissions.rules.map((r,i)=>`<div class="accordion-item neu"><button class="accordion-trigger">${i+1}. ${escapeHtml(r)} <span>+</span></button><div class="accordion-content">This rule is presented from the school’s published admission information.</div></div>`).join('')}</div>${enquiryForm('Admission Enquiry')}</div></div></section>`;
routes['/admissions/guidelines'] = routes['/admissions'];
routes['/admissions/minimum-age'] = () => `<section class="section"><div class="container">${pageHero('Admissions','Minimum Age','Official age criteria should be confirmed against the latest school admission guidelines.') }<div class="neu results-wrap"><table class="results-table"><thead><tr><th>Stage</th><th>Requirement</th></tr></thead><tbody>${DATA.admissions.minimumAge.map(x=>`<tr><td>${x.stage}</td><td>${x.age}</td></tr>`).join('')}</tbody></table></div></div></section>`;

routes['/campus/facilities'] = () => `<section class="section"><div class="container">${pageHero('Campus','Facilities','Facilities listed in the school’s public-facing information, with descriptions kept intentionally factual.') }<div class="grid-4">${DATA.facilities.map(f=>`<article class="card neu facility"><div class="icon">${f.icon}</div><h3>${f.title}</h3><p>${f.description}</p><div class="image-placeholder" style="min-height:150px;margin-top:16px">${placeholder(f.title.toUpperCase()+' IMAGE')}</div></article>`).join('')}</div></div></section>`;
routes['/campus/infrastructure'] = () => `<section class="section"><div class="container">${pageHero('Campus','Infrastructure','Published infrastructure figures are shown verbatim; verify measurements with school administration before final publication.') }<div class="grid-3">${DATA.infrastructure.map(i=>`<div class="stat neu"><div class="label">${i.label}</div><div class="value" style="font-size:1.7rem">${i.value}</div></div>`).join('')}</div><div class="callout neu" style="margin-top:24px">Verify infrastructure measurements with school administration before final publication.</div></div></section>`;
routes['/campus/gallery'] = () => `<section class="section"><div class="container">${pageHero('Campus','Gallery','Replace placeholders with official school photographs only.') }<div class="tabs" id="gallery-tabs">${['All','Campus','Students','Academics','Sports','Events','Activities','Facilities'].map((x,i)=>`<button class="tab ${i===0?'active':''}" data-gallery-filter="${x}">${x}</button>`).join('')}</div><div class="gallery" id="gallery-grid"></div></div></section>`;

routes['/student-life'] = () => `<section class="section"><div class="container">${pageHero('Student Life','Student Life & Activities','Structured categories for verified school activities; unsupported details remain explicit placeholders.') }<div class="grid-3">${['Academic Activities','Sports','Cultural Activities','Creative Activities','Clubs','Eco Club'].map((x,i)=>card(['▣','◉','✦','✎','♧','♢'][i],x,'[Add official activity details]','')).join('')}</div></div></section>`;
routes['/rules-regulations'] = () => `<section class="section"><div class="container">${pageHero('Policies','Rules & Regulations','A policy shell designed to receive the school’s official rules without inventing them.') }<div>${['Student Discipline','Attendance','Uniform','Campus Conduct','Technology Usage','Safety','Visitor Rules'].map((x,i)=>`<div class="accordion-item neu"><button class="accordion-trigger">${x}<span>+</span></button><div class="accordion-content">[Official school policy to be added]</div></div>`).join('')}</div></div></section>`;

routes['/disclosure'] = () => `<section class="section"><div class="container">${pageHero('Disclosure','Mandatory Public Disclosure','An official-style document centre aligned to the published disclosure structure.') }<div class="grid-4" style="margin-bottom:24px"><div class="stat neu"><div class="label">School</div><div class="value" style="font-size:1.25rem">${DATA.school.name}</div></div><div class="stat neu"><div class="label">Affiliation No.</div><div class="value">${DATA.school.affiliationNo}</div></div><div class="stat neu"><div class="label">School Code</div><div class="value">${DATA.school.schoolCode}</div></div><div class="stat neu"><div class="label">Principal</div><div class="value" style="font-size:1.25rem">${DATA.school.principal.name}</div></div></div><div class="filters"><div class="tabs" id="doc-filters">${['All','Affiliation','Certification','Safety','Academics','Governance','Results','Staff','Infrastructure'].map((x,i)=>`<button class="tab ${i===0?'active':''}" data-doc-filter="${x}">${x}</button>`).join('')}</div><div class="search"><input id="doc-search" placeholder="Search documents…" aria-label="Search documents"></div></div><div class="doc-grid" id="doc-grid"></div></div></section>`;
routes['/disclosure/documents'] = routes['/disclosure'];

routes['/contact'] = () => `<section class="section"><div class="container">${pageHero('Contact','Contact School','Use the official published contact details below. Coordinates and map integrations remain intentionally unset.') }<div class="split"><div><div class="card neu"><div class="kicker">School</div><h3>${DATA.school.name}</h3><p>${DATA.school.address}</p><div class="footer-list" style="margin-top:14px"><a class="neu-btn" href="tel:+917884216647">0788-4216647</a><a class="neu-btn" href="tel:+917884216642">0788-4216642</a><a class="neu-btn" href="tel:+916266434635">6266434635</a><a class="neu-btn" href="mailto:${DATA.school.email}">${DATA.school.email}</a></div></div><div style="height:18px"></div><div class="map-placeholder neu"><div class="map-inner"><div><strong>Directions / map area</strong><div style="color:var(--muted);margin-top:6px">Official coordinates or school-approved map embed to be inserted.</div></div></div></div></div>${contactForm()}</div></div></section>`;

function enquiryForm(title){return `<form class="form neu" data-form="enquiry"><div class="section-heading" style="margin-bottom:18px"><div class="kicker">${title}</div><h2 style="font-size:2rem">Tell the school what you need.</h2></div><div class="form-grid"><div class="field"><label for="student-name">Student Name</label><input id="student-name" name="studentName" required></div><div class="field"><label for="parent-name">Parent/Guardian Name</label><input id="parent-name" name="parentName" required></div><div class="field"><label for="class-applying">Class Applying For</label><select id="class-applying" name="class"><option value="">Select a class</option>${['Nursery','Pre-Primary I','Pre-Primary II',...Array.from({length:12},(_,i)=>`Class ${i+1}`)].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" inputmode="tel" required></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required></div><div class="field full"><label for="message">Message</label><textarea id="message" name="message"></textarea></div></div><button class="neu-btn primary" type="submit">Send Enquiry</button><div class="status" role="status"></div><div class="form-note">This demo validates the form locally. Connect it to an approved backend service before production use.</div></form>`}
function contactForm(){return `<form class="form neu" data-form="contact"><div class="section-heading" style="margin-bottom:18px"><div class="kicker">Contact</div><h2 style="font-size:2rem">Send a message.</h2></div><div class="form-grid"><div class="field"><label for="c-name">Name</label><input id="c-name" name="name" required></div><div class="field"><label for="c-email">Email</label><input id="c-email" name="email" type="email" required></div><div class="field"><label for="c-phone">Phone</label><input id="c-phone" name="phone" inputmode="tel"></div><div class="field"><label for="c-subject">Subject</label><input id="c-subject" name="subject" required></div><div class="field full"><label for="c-message">Message</label><textarea id="c-message" name="message" required></textarea></div></div><button class="neu-btn primary" type="submit">Send Message</button><div class="status" role="status"></div><div class="form-note">No live submission endpoint is included in this demo.</div></form>`}

function currentTitle(){return ({'/':'Home','/about':'About','/about/journey':'Our Journey','/about/principal':'Principal’s Message','/about/vision-values':'Vision & Values','/academics':'Academics','/academics/curriculum':'Curriculum','/academics/calendar':'Academic Calendar','/academics/book-list':'Book List','/academics/teachers':'Teachers & Staff','/academics/results':'Results','/admissions':'Admissions','/admissions/guidelines':'Admission Guidelines','/admissions/minimum-age':'Minimum Age','/campus/facilities':'Facilities','/campus/infrastructure':'Infrastructure','/campus/gallery':'Gallery','/student-life':'Student Life','/rules-regulations':'Rules & Regulations','/disclosure':'Disclosure','/disclosure/documents':'Documents','/contact':'Contact'}[location.pathname]||'Page');}

function render(){
  const path=location.pathname.replace(/\/$/,'')||'/'; const view=routes[path] || (()=>`<section class="section"><div class="container">${pageHero('Page not found','404','The requested page is not part of this site architecture.')}<a class="neu-btn primary" href="/">Return Home</a></div></section>`);
  $('#app').innerHTML=layout(view());
  bindGlobal(); bindPage(path);
}
function go(url){history.pushState({},'',url);render();window.scrollTo({top:0,behavior:'smooth'})}

function bindGlobal(){
  $$('.nav-link,.brand,.nav-cta,.mobile-drawer a,.footer a').forEach(a=>{const href=a.getAttribute('href'); if(href && href.startsWith('/')) a.addEventListener('click',e=>{e.preventDefault();go(href)})});
  $('#menu-open')?.addEventListener('click',()=>$('#mobile-drawer').classList.add('open'));
  $('#menu-close')?.addEventListener('click',()=>$('#mobile-drawer').classList.remove('open'));
  $$('.accordion-trigger').forEach(b=>b.addEventListener('click',()=>{const item=b.closest('.accordion-item');item.classList.toggle('open');b.querySelector('span').textContent=item.classList.contains('open')?'−':'+'}));
  $$('.tab[data-tab]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.tab; $$('.tab[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===key)); $$('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===key))}));
  $$('form[data-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const s=$('.status',form);if(!form.checkValidity()){s.className='status show err';s.textContent='Please complete the required fields.';return;}s.className='status show ok';s.textContent='Form validated locally. Connect this form to the school’s approved backend before live submission.';form.reset()}));
  $('#lightbox-close')?.addEventListener('click',()=>closeLightbox());$('#lightbox')?.addEventListener('click',e=>{if(e.target.id==='lightbox')closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()},{once:true});
}
function bindPage(path){
  if(path==='/'||path==='/academics/results') renderResults(path==='/'?'#home-results':'#results-page');
  if(path==='/academics/teachers') renderStaff();
  if(path==='/disclosure'||path==='/disclosure/documents') renderDocs();
  if(path==='/campus/gallery') renderGallery();
  if(path==='/academics/book-list') $('#book-search')?.addEventListener('input',()=>{});
  $$('[data-nav-placeholder]').forEach(x=>x.addEventListener('click',()=>{}));
  $$('[href^="/"]').forEach(a=>{if(a.dataset.bound)return;a.dataset.bound='1';a.addEventListener('click',e=>{const href=a.getAttribute('href');if(href&&href.startsWith('/')){e.preventDefault();go(href)}})});
}
function renderResults(target){const el=$(target);if(!el)return;let key='classXII';const make=k=>{const rows=DATA.results[k].map(r=>`<tr><td>${r.year}</td><td>${r.registered}</td><td>${r.passed}</td><td>${r.percentage.toFixed(2)}%</td><td style="min-width:180px"><div class="bar"><span style="--w:${r.percentage}%"></span></div></td></tr>`).join('');return `<div class="neu results-wrap"><table class="results-table"><thead><tr><th>Year</th><th>Registered</th><th>Passed</th><th>Pass %</th><th>Visual</th></tr></thead><tbody>${rows}</tbody></table></div>`};el.innerHTML=make(key);if(target==='#results-page'){$$('[data-result-tab]').forEach(b=>b.addEventListener('click',()=>{ $$('[data-result-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');el.innerHTML=make(b.dataset.resultTab)}));} else el.previousElementSibling?.querySelectorAll('[data-result-tab]')}
function renderStaff(){const grid=$('#staff-grid');const render=(filter='All',q='')=>{const items=DATA.faculty.filter(x=>(filter==='All'||x.designation===filter)&&`${x.name} ${x.subject}`.toLowerCase().includes(q.toLowerCase()));grid.innerHTML=items.length?items.map(x=>`<article class="card neu"><div class="image-placeholder" style="min-height:180px">${placeholder('STAFF PHOTO')}</div><div class="kicker" style="margin-top:16px">${x.designation}</div><h3>${x.name}</h3><p><strong>${x.qualification}</strong><br>${x.subject}</p></article>`).join(''):`<div class="card neu"><p>No verified staff record matches that filter.</p></div>`};render();let filter='All';$$('[data-staff-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-staff-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.staffFilter;render(filter,$('#staff-search').value)}));$('#staff-search')?.addEventListener('input',e=>render(filter,e.target.value));}
function renderDocs(){const grid=$('#doc-grid');let filter='All';const draw=(f='All',q='')=>{const items=DATA.documents.filter(x=>(f==='All'||x.category===f)&&`${x.title} ${x.category}`.toLowerCase().includes(q.toLowerCase()));grid.innerHTML=items.map(x=>`<article class="doc-card neu"><div class="doc-meta"><span>${x.category}</span><span class="tag">${x.status}</span></div><h3>${x.title}</h3><p style="color:var(--muted)">Official document placeholder. Upload the approved PDF at <code>${x.path}</code>.</p><div class="doc-actions"><button class="neu-btn" type="button" data-doc-action="view">View PDF</button><button class="neu-btn" type="button" data-doc-action="download">Download PDF</button></div></article>`).join('')};draw();$$('[data-doc-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-doc-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.docFilter;draw(filter,$('#doc-search').value)}));$('#doc-search')?.addEventListener('input',e=>draw(filter,e.target.value));}
function renderGallery(){const grid=$('#gallery-grid');let filter='All';const draw=(f='All')=>{grid.innerHTML=DATA.gallery.filter(x=>f==='All'||x.category===f).map((x,i)=>`<article class="gallery-item" tabindex="0" data-gallery-index="${i}" aria-label="Open ${x.title}"><div class="ph"><div><strong>[${x.title.toUpperCase()}]</strong><small style="display:block;color:var(--muted);margin-top:8px">${x.category}</small></div></div><div class="caption">${x.title}</div></article>`).join('');$$('.gallery-item',grid).forEach(item=>{item.addEventListener('click',()=>openLightbox(DATA.gallery[item.dataset.galleryIndex]));item.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openLightbox(DATA.gallery[item.dataset.galleryIndex])})})};draw();$$('[data-gallery-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-gallery-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.galleryFilter;draw(filter)}));}
function openLightbox(item){const lb=$('#lightbox');const body=$('#lightbox-body');body.innerHTML=`<div><strong>[${escapeHtml(item.title.toUpperCase())}]</strong><div style="margin-top:8px;color:var(--muted)">${escapeHtml(item.category)} · Replace with official photo</div></div>`;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}
function closeLightbox(){const lb=$('#lightbox');if(lb){lb.classList.remove('open');lb.setAttribute('aria-hidden','true')}}
window.addEventListener('popstate',render);

(async()=>{await loadData();render()})();
